# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{awardable}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Benjamin Yu"]
  s.date = %q{2009-12-22}
  s.description = %q{
      Awardable is a Ruby on Rails plugin for projects that want to give
      badges (or trophies, or achievements) to their Users (or any other
      ActiveRecord model).}
  s.email = %q{benjaminlyu@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "Gemfile",
     "LICENSE",
     "NOTICE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "features/awardable.feature",
     "features/step_definitions/awardable_steps.rb",
     "features/support/env.rb",
     "generators/awardable_generator.rb",
     "generators/templates/app/models/award.rb",
     "generators/templates/app/models/awarding.rb",
     "generators/templates/db/migrate/migration.rb",
     "lib/awardable.rb",
     "lib/awardable/acts_as_awardable.rb",
     "lib/awardable/award_base.rb",
     "lib/awardable/awarding_base.rb",
     "spec/awardable/acts_as_awardable_spec.rb",
     "spec/awardable/awarding_base_spec.rb",
     "spec/schema.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/byu/awardable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{An awards, achievements and badges plugin for Rails.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

