# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{awardable}
  s.version = "0.1.0.alpha"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Benjamin Yu}]
  s.date = %q{2011-05-27}
  s.description = %q{
    Awardable is a Ruby on Rails plugin for projects that want to give
    badges (or trophies, or achievements) to their Users (or any other
    ActiveRecord model).}
  s.email = %q{benjaminlyu@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "NOTICE",
    "README.md",
    "Rakefile",
    "awardable.gemspec",
    "generators/awardable_generator.rb",
    "generators/templates/app/models/award.rb",
    "generators/templates/app/models/awarding.rb",
    "generators/templates/db/migrate/migration.rb",
    "lib/awardable.rb",
    "lib/awardable/acts_as_awardable.rb",
    "lib/awardable/award_base.rb",
    "lib/awardable/awarding_base.rb",
    "lib/awardable/version.rb",
    "spec/awardable/acts_as_awardable_spec.rb",
    "spec/awardable/awarding_base_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/support/active_record_test_db.rb",
    "spec/support/schema.rb"
  ]
  s.homepage = %q{http://github.com/byu/awardable}
  s.licenses = [%q{APACHE-2.0}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.2}
  s.summary = %q{An awards, achievements and badges plugin for Rails.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<activerecord>, ["~> 3.0.7"])
      s.add_development_dependency(%q<activesupport>, ["~> 3.0.7"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<activerecord>, ["~> 3.0.7"])
      s.add_dependency(%q<activesupport>, ["~> 3.0.7"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<activerecord>, ["~> 3.0.7"])
    s.add_dependency(%q<activesupport>, ["~> 3.0.7"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
  end
end

